/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Medical;

import Login.Doctor;
import Login.Login;
import javax.swing.table.DefaultTableModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.awt.print.PrinterException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Yash Somani
 */
public class MedicalPri extends javax.swing.JFrame {

    /**
     * Creates new form Hospital
     */
    public MedicalPri() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jtxtPationtStorageAdvice = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtxtPatientDrivingandusingmachines = new javax.swing.JTextField();
        jtxtPatientRef = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtxtPatientUseMadication = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jtxtPatientDose = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtxtPatientPatientID = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jtxtPatientLOT = new javax.swing.JTextField();
        jtxtPatientNHS = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jNameTablete = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jtxtPatientIssuedDate = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jtxtPatientName = new javax.swing.JTextField();
        jtxtPatientExpDate = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jtxtPatientDOB = new javax.swing.JTextField();
        jtxtPatientDailyDose = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jtxtPatientAddress = new javax.swing.JTextField();
        jtxtPatientTabletNo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtPrescription = new javax.swing.JTextArea();
        jtxtPatientPossibleSideEffect = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jtxtPationtFurtherInfo = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hospital");

        jPanel7.setBackground(new java.awt.Color(0, 0, 0));
        jPanel7.setForeground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxtPationtStorageAdvice.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel7.add(jtxtPationtStorageAdvice, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 290, 270, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Driving and Using Machines:");
        jPanel7.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 340, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Reference No:");
        jPanel7.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        jtxtPatientDrivingandusingmachines.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel7.add(jtxtPatientDrivingandusingmachines, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 340, 270, -1));

        jtxtPatientRef.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel7.add(jtxtPatientRef, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, 270, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("How To Use Medication:");
        jPanel7.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 390, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Name Of Tablets:");
        jPanel7.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        jtxtPatientUseMadication.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel7.add(jtxtPatientUseMadication, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 390, 270, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Dose (mg):");
        jPanel7.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Patient ID:");
        jPanel7.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 440, -1, -1));

        jtxtPatientDose.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel7.add(jtxtPatientDose, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, 270, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("LOT:");
        jPanel7.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, -1, -1));

        jtxtPatientPatientID.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel7.add(jtxtPatientPatientID, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 440, 270, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("NHS Number:");
        jPanel7.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 490, -1, -1));

        jtxtPatientLOT.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel7.add(jtxtPatientLOT, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 440, 270, -1));

        jtxtPatientNHS.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel7.add(jtxtPatientNHS, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 490, 270, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Issued Date:");
        jPanel7.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, -1, -1));

        jNameTablete.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jNameTablete.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Option", "Ibuprofen", "Co-codamol", "Paracetamol", "Amlodipine" }));
        jNameTablete.setMinimumSize(new java.awt.Dimension(6, 35));
        jNameTablete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNameTableteActionPerformed(evt);
            }
        });
        jPanel7.add(jNameTablete, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 270, -1));

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 51), 3));

        jButton1.setText("Update");
        jButton1.setPreferredSize(new java.awt.Dimension(100, 0));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton20.setText("Delete");
        jButton20.setPreferredSize(new java.awt.Dimension(100, 0));
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });

        jButton21.setText("Doctor");
        jButton21.setPreferredSize(new java.awt.Dimension(100, 0));
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });

        jButton23.setText("Prescription");
        jButton23.setPreferredSize(new java.awt.Dimension(100, 0));
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });

        jButton24.setText("Login");
        jButton24.setPreferredSize(new java.awt.Dimension(100, 0));
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });

        jButton26.setText("Reset");
        jButton26.setPreferredSize(new java.awt.Dimension(100, 0));
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });

        jButton27.setText("Exit");
        jButton27.setPreferredSize(new java.awt.Dimension(100, 0));
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27ActionPerformed(evt);
            }
        });

        jButton28.setText("Print");
        jButton28.setPreferredSize(new java.awt.Dimension(100, 0));
        jButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton28ActionPerformed(evt);
            }
        });

        jButton25.setText("Help");
        jButton25.setPreferredSize(new java.awt.Dimension(100, 0));
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });

        jButton29.setText("Payment");
        jButton29.setPreferredSize(new java.awt.Dimension(100, 0));
        jButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton29ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30)
                .addComponent(jButton20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30)
                .addComponent(jButton21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30)
                .addComponent(jButton29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30)
                .addComponent(jButton25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30)
                .addComponent(jButton26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30)
                .addComponent(jButton23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30)
                .addComponent(jButton24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30)
                .addComponent(jButton28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30)
                .addComponent(jButton27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(54, 54, 54))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(jButton20, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(jButton21, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(jButton26, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(jButton23, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(jButton24, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(jButton28, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(jButton27, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(jButton25, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(jButton29, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addGap(16, 16, 16))
        );

        jPanel7.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 700, 1380, 70));

        jtxtPatientIssuedDate.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel7.add(jtxtPatientIssuedDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 490, 270, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Patient Name");
        jPanel7.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 540, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Exp Date:");
        jPanel7.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, -1, -1));

        jtxtPatientName.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel7.add(jtxtPatientName, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 540, 270, -1));

        jtxtPatientExpDate.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel7.add(jtxtPatientExpDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 540, 270, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Date Of Birth");
        jPanel7.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 590, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Daily Dose:");
        jPanel7.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 590, -1, -1));

        jtxtPatientDOB.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel7.add(jtxtPatientDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 590, 270, -1));

        jtxtPatientDailyDose.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel7.add(jtxtPatientDailyDose, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 590, 270, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Patient Address");
        jPanel7.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 640, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Number Of Tablets:");
        jPanel7.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, -1, -1));

        jtxtPatientAddress.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel7.add(jtxtPatientAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 640, 270, -1));

        jtxtPatientTabletNo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel7.add(jtxtPatientTabletNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 390, 270, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Possible Side Effects:");
        jPanel7.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 650, -1, -1));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 255, 102), 5));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 60)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Medical Management System");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(372, 372, 372)
                .addComponent(jLabel1)
                .addContainerGap(373, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel7.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1639, -1));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255), 3));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Patient Prescription");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(370, 370, 370)
                .addComponent(jLabel3)
                .addContainerGap(348, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        jPanel7.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 51), 3));

        jtxtPrescription.setColumns(20);
        jtxtPrescription.setRows(5);
        jScrollPane1.setViewportView(jtxtPrescription);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 140, -1, -1));

        jtxtPatientPossibleSideEffect.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel7.add(jtxtPatientPossibleSideEffect, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 640, 270, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Further Information:");
        jPanel7.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 240, -1, -1));

        jtxtPationtFurtherInfo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel7.add(jtxtPationtFurtherInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 240, 270, -1));

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 255, 153), 3));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name Of Tablet", "Reference No", "Dose (mg)", "Number Of Tablets", "LOT", "Issued date", "Exp Date", "Daily Dose", "Possible Side Effects", "Further Information", "Storage Advice", "Driving and Using Machines", "Title 13 How to Use Madication", "Patient ID", "NHS Number", "Patient Name", "Date Of Birth", "Patient Address"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 780, 1639, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Storage Advice:");
        jPanel7.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 290, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 973, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{
                jNameTablete.getSelectedItem().toString(),
                jtxtPatientRef.getText(),
                jtxtPatientDose.getText(),
                jtxtPatientTabletNo.getText(),
                jtxtPatientLOT.getText(),
                jtxtPatientIssuedDate.getText(),
                jtxtPatientExpDate.getText(),
                jtxtPatientDailyDose.getText(),
                jtxtPatientPossibleSideEffect.getText(),
                jtxtPationtFurtherInfo.getText(),
                jtxtPationtStorageAdvice.getText(),
                jtxtPatientDrivingandusingmachines.getText(),
                jtxtPatientUseMadication.getText(),
                jtxtPatientPatientID.getText(),
                jtxtPatientNHS.getText(),
                jtxtPatientName.getText(),
                jtxtPatientDOB.getText(),
                jtxtPatientAddress.getText(),
        });
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jNameTableteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNameTableteActionPerformed
        // TODO add your handling code here:
        if(jNameTablete.getSelectedItem().equals("Select Option")){
            jtxtPatientRef.setText("");
            jtxtPatientDose.setText("");
            jtxtPatientTabletNo.setText("");
            jtxtPatientLOT.setText("");
            jtxtPatientIssuedDate.setText("");
            jtxtPatientExpDate.setText("");
            jtxtPatientDailyDose.setText("");
            jtxtPatientPossibleSideEffect.setText("");
            jtxtPationtFurtherInfo.setText("");
            jtxtPationtStorageAdvice.setText("");
            jtxtPatientDrivingandusingmachines.setText("");
            jtxtPatientUseMadication.setText("");
            jtxtPatientPatientID.setText("");
            jtxtPatientNHS.setText("");
            jtxtPatientName.setText("");
            jtxtPatientDOB.setText("");
            jtxtPatientAddress.setText("");
        }
        else if(jNameTablete.getSelectedItem().equals("Paracetamol")){
            jtxtPatientRef.setText("PAR1800180221");
            jtxtPatientDose.setText("4");
            jtxtPatientTabletNo.setText("22");
            jtxtPatientLOT.setText("62775875");
            jtxtPatientIssuedDate.setText("02/08/2019");
            jtxtPatientExpDate.setText("07/01/2022");
            jtxtPatientDailyDose.setText("3");
            jtxtPatientPossibleSideEffect.setText("Jaundice, Dark Urine");
            jtxtPationtFurtherInfo.setText("Place Dispensary");
            jtxtPationtStorageAdvice.setText("Less Than 10%");
            jtxtPatientDrivingandusingmachines.setText("No");
            jtxtPatientUseMadication.setText("Use Water, No Alcohol");
            jtxtPatientPatientID.setText("P973213");
            jtxtPatientNHS.setText("791223");
            jtxtPatientName.setText("");
            jtxtPatientDOB.setText("");
            jtxtPatientAddress.setText("");
        }
        else if(jNameTablete.getSelectedItem().equals("Co-codamol")){
            jtxtPatientRef.setText("COCO8749733");
            jtxtPatientDose.setText("5");
            jtxtPatientTabletNo.setText("25");
            jtxtPatientLOT.setText("5610078375");
            jtxtPatientIssuedDate.setText("28/07/2020");
            jtxtPatientExpDate.setText("21/12/2022");
            jtxtPatientDailyDose.setText("2");
            jtxtPatientPossibleSideEffect.setText("Dizziness");
            jtxtPationtFurtherInfo.setText("Place Dispensary");
            jtxtPationtStorageAdvice.setText("Less Than 7%");
            jtxtPatientDrivingandusingmachines.setText("No");
            jtxtPatientUseMadication.setText("Use Water and Milk");
            jtxtPatientPatientID.setText("P986863");
            jtxtPatientNHS.setText("646633");
            jtxtPatientName.setText("");
            jtxtPatientDOB.setText("");
            jtxtPatientAddress.setText("");
        }
        else if (jNameTablete.getSelectedItem().equals("Ibuprofen")){
            jtxtPatientRef.setText("IBU1800180221");
            jtxtPatientDose.setText("2");
            jtxtPatientTabletNo.setText("32");
            jtxtPatientLOT.setText("561005875");
            jtxtPatientIssuedDate.setText("06/05/2020");
            jtxtPatientExpDate.setText("04/05/2022");
            jtxtPatientDailyDose.setText("4");
            jtxtPatientPossibleSideEffect.setText("Bleeding");
            jtxtPationtFurtherInfo.setText("Place Dispensary");
            jtxtPationtStorageAdvice.setText("Less Than 20%");
            jtxtPatientDrivingandusingmachines.setText("No");
            jtxtPatientUseMadication.setText("Use Water, No Alcohol");
            jtxtPatientPatientID.setText("P976863");
            jtxtPatientNHS.setText("646543");
            jtxtPatientName.setText("");
            jtxtPatientDOB.setText("");
            jtxtPatientAddress.setText("");
        }
        else if (jNameTablete.getSelectedItem().equals("Amlodipine")){
            jtxtPatientRef.setText("IBU1800180221");
            jtxtPatientDose.setText("2");
            jtxtPatientTabletNo.setText("32");
            jtxtPatientLOT.setText("561005875");
            jtxtPatientIssuedDate.setText("06/05/2020");
            jtxtPatientExpDate.setText("04/05/2022");
            jtxtPatientDailyDose.setText("4");
            jtxtPatientPossibleSideEffect.setText("Bleeding");
            jtxtPationtFurtherInfo.setText("Place Dispensary");
            jtxtPationtStorageAdvice.setText("Less Than 20%");
            jtxtPatientDrivingandusingmachines.setText("No");
            jtxtPatientUseMadication.setText("Use Water, No Alcohol");
            jtxtPatientPatientID.setText("P976863");
            jtxtPatientNHS.setText("646543");
            jtxtPatientName.setText("");
            jtxtPatientDOB.setText("");
            jtxtPatientAddress.setText("");
        }
    }//GEN-LAST:event_jNameTableteActionPerformed

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed
        // TODO add your handling code here:
        JFrame frame = new JFrame("Exit");
        if(JOptionPane.showConfirmDialog(frame,"Confirm If you want to exit","Medical Management System",JOptionPane.YES_NO_OPTION )== JOptionPane.YES_NO_OPTION){
            setVisible(false);
        }
    }//GEN-LAST:event_jButton27ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        // TODO add your handling code here:
        Login iLogin = new Login();
        iLogin.setVisible(true);
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        // TODO add your handling code here:
        jtxtPrescription.setEditable(true);
        String qty1 = (jtxtPatientRef.getText());
        String qty2 = (jtxtPatientDose.getText());
        String qty3 = (jtxtPatientTabletNo.getText());
        String qty4 = (jtxtPatientLOT.getText());
        String qty5 = (jtxtPatientDailyDose.getText());
        String qty6 = (jtxtPatientPossibleSideEffect.getText());
        String qty7 = (jtxtPationtFurtherInfo.getText());
        String qty8 = (jtxtPatientUseMadication.getText());
        String qty9 = (jtxtPatientPatientID.getText());
        String qty10 = (jtxtPatientName.getText());
        String qty11 = (jtxtPatientDOB.getText());
        String qty12 = (jtxtPatientAddress.getText());
        String qty13 = (jNameTablete.getSelectedItem().toString());

        jtxtPrescription.setText("");
        jtxtPrescription.append("\t\n\tMediacal Management System\n"
        +"\nPatient ID:\t\t"+qty9
        +"\nPatient Name:\t\t"+qty10
        +"\nDate Of Birth:\t\t"+qty11
        +"\nPatient Address:\t"+qty12
        +"\nPrescription:\t\t"+qty13
        +"\n\nReference No:\t\t"+qty1
        +"\nDose (mg):\t\t"+qty2
        +"\nNumber of Tabblet\t"+qty3
        +"\nLOY:\t\t"+qty4
        +"\nDaily Dose:\t\t"+qty5
        +"\nPossible Side Effect:\t"+qty6
        +"\nFurther Information:\t"+qty7
        +"\nHow to Use Medication:\t"+qty8
        +"\n\n          Patient Instruction we have introduced a free text confirmation\n\t"
        +"TEXT REMINDERS FOR APPOINTMENT");
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton28ActionPerformed
        // TODO add your handling code here:
        try{
            jtxtPrescription.print();
        }catch (PrinterException ex){
            Logger.getLogger(MedicalPri.class.getName()).log(Level.SEVERE,null,ex);
        }
    }//GEN-LAST:event_jButton28ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        // TODO add your handling code here:
        Doctor iDoctor = new Doctor();
        iDoctor.setVisible(true);
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
        // TODO add your handling code here:
            jNameTablete.setSelectedIndex(0);
            jtxtPatientRef.setText("");
            jtxtPatientDose.setText("");
            jtxtPatientTabletNo.setText("");
            jtxtPatientLOT.setText("");
            jtxtPatientIssuedDate.setText("");
            jtxtPatientExpDate.setText("");
            jtxtPatientDailyDose.setText("");
            jtxtPatientPossibleSideEffect.setText("");
            jtxtPationtFurtherInfo.setText("");
            jtxtPationtStorageAdvice.setText("");
            jtxtPatientDrivingandusingmachines.setText("");
            jtxtPatientUseMadication.setText("");
            jtxtPatientPatientID.setText("");
            jtxtPatientNHS.setText("");
            jtxtPatientName.setText("");
            jtxtPatientDOB.setText("");
            jtxtPatientAddress.setText("");
            jtxtPrescription.setText("");
    }//GEN-LAST:event_jButton26ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        if(jTable1.getSelectedRow() == -1){
            if(jTable1.getRowCount() == 0) {
                JOptionPane.showMessageDialog(null,"No Data To Delete","Medical Management System",JOptionPane.OK_OPTION);
            }
            else {
                JOptionPane.showMessageDialog(null,"Select A Row To Delete","Medical Management System",JOptionPane.OK_OPTION);
            }
        }
        else {
            model.removeRow(jTable1.getSelectedRow());
        }
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
        // TODO add your handling code here:
        Help iHelp = new Help();
        iHelp.setVisible(true);
    }//GEN-LAST:event_jButton25ActionPerformed

    private void jButton29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton29ActionPerformed
        // TODO add your handling code here:
        Payment iPayment = new Payment();
        iPayment.setVisible(true);
    }//GEN-LAST:event_jButton29ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MedicalPri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MedicalPri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MedicalPri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MedicalPri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MedicalPri().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> jNameTablete;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jtxtPatientAddress;
    private javax.swing.JTextField jtxtPatientDOB;
    private javax.swing.JTextField jtxtPatientDailyDose;
    private javax.swing.JTextField jtxtPatientDose;
    private javax.swing.JTextField jtxtPatientDrivingandusingmachines;
    private javax.swing.JTextField jtxtPatientExpDate;
    private javax.swing.JTextField jtxtPatientIssuedDate;
    private javax.swing.JTextField jtxtPatientLOT;
    private javax.swing.JTextField jtxtPatientNHS;
    private javax.swing.JTextField jtxtPatientName;
    private javax.swing.JTextField jtxtPatientPatientID;
    private javax.swing.JTextField jtxtPatientPossibleSideEffect;
    private javax.swing.JTextField jtxtPatientRef;
    private javax.swing.JTextField jtxtPatientTabletNo;
    private javax.swing.JTextField jtxtPatientUseMadication;
    private javax.swing.JTextField jtxtPationtFurtherInfo;
    private javax.swing.JTextField jtxtPationtStorageAdvice;
    private javax.swing.JTextArea jtxtPrescription;
    // End of variables declaration//GEN-END:variables
}
