/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login;
import Medical.Help;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Yash Somani
 */
public class Doctor extends javax.swing.JFrame {

    /**
     * Creates new form Doctor
     */
    public Doctor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jtxtPostCode = new javax.swing.JTextField();
        jtxAddressCenter = new javax.swing.JTextField();
        jtxtPatientID = new javax.swing.JTextField();
        jtxtMedicalCenterName = new javax.swing.JTextField();
        jtxtSurname = new javax.swing.JTextField();
        jtxtFirstname = new javax.swing.JTextField();
        jtxtRef1 = new javax.swing.JTextField();
        jNameTablete = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jtxtGPAppintmentRef = new javax.swing.JTextField();
        jtxtEMISNo = new javax.swing.JTextField();
        jtxtPatientNHS = new javax.swing.JTextField();
        jtxtEmailAddress = new javax.swing.JTextField();
        jtxtFaxNo = new javax.swing.JTextField();
        jtxtOfficeMobNo2 = new javax.swing.JTextField();
        jtxtOfficeMobNo1 = new javax.swing.JTextField();
        jtxtMedicalCenterRef = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Doctor");

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 51), 5));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Doctor's Ref No:");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 18, -1, -1));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Doctors NHS No:");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 68, -1, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Firstname:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 118, -1, -1));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Surname:");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 168, -1, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Medical Center Name:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 218, -1, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Patient ID:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 268, -1, -1));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Address of Center:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 318, -1, -1));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Post Code:");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 368, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 51), 3));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("Medical");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setText("Help");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton8.setText("Login");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton9.setText("Exit");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, jButton2, jButton3, jButton6, jButton8, jButton9});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton1, jButton2, jButton3, jButton6, jButton8, jButton9});

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Doctor's Ref No", "Doctors NHS No", "Firstname", "Surname", "Medical Center Name", "Patient ID", "Address of Center", "Post Code", "Medical Center Ref", "Office Phone No 1", "Office Phone No 2", "Fax No", "Email Address", "Patient NHS No", "EMIS No", "GP Appointment Ref"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 525, 1324, 290));

        jtxtPostCode.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel3.add(jtxtPostCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 368, 270, -1));

        jtxAddressCenter.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel3.add(jtxAddressCenter, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 318, 270, -1));

        jtxtPatientID.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel3.add(jtxtPatientID, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 268, 270, -1));

        jtxtMedicalCenterName.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel3.add(jtxtMedicalCenterName, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 218, 270, -1));

        jtxtSurname.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel3.add(jtxtSurname, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 168, 270, -1));

        jtxtFirstname.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel3.add(jtxtFirstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 118, 270, -1));

        jtxtRef1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jtxtRef1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtRef1ActionPerformed(evt);
            }
        });
        jPanel3.add(jtxtRef1, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 68, 270, -1));

        jNameTablete.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jNameTablete.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Doctor Ref", "DRRE983984", "DRRE345678", "DRRE567833", "DRRE308164", "DRRE486100" }));
        jNameTablete.setMinimumSize(new java.awt.Dimension(6, 35));
        jNameTablete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNameTableteActionPerformed(evt);
            }
        });
        jPanel3.add(jNameTablete, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 18, 270, -1));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Medical Center Ref:");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 21, -1, -1));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Office Phone No. 1:");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 68, -1, -1));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Office Phone No. 2:");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 118, -1, -1));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Fax No:");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 168, -1, -1));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Email Address:");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 218, -1, -1));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Patient NHS Number:");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 268, -1, -1));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("EMIS Number:");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 318, -1, -1));

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("GP Appointment Ref:");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 368, -1, -1));

        jtxtGPAppintmentRef.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel3.add(jtxtGPAppintmentRef, new org.netbeans.lib.awtextra.AbsoluteConstraints(1053, 368, 270, -1));

        jtxtEMISNo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel3.add(jtxtEMISNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1053, 318, 270, -1));

        jtxtPatientNHS.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel3.add(jtxtPatientNHS, new org.netbeans.lib.awtextra.AbsoluteConstraints(1053, 268, 270, -1));

        jtxtEmailAddress.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel3.add(jtxtEmailAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(1053, 218, 270, -1));

        jtxtFaxNo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel3.add(jtxtFaxNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1053, 168, 270, -1));

        jtxtOfficeMobNo2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel3.add(jtxtOfficeMobNo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1053, 118, 270, -1));

        jtxtOfficeMobNo1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel3.add(jtxtOfficeMobNo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1053, 68, 270, -1));

        jtxtMedicalCenterRef.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel3.add(jtxtMedicalCenterRef, new org.netbeans.lib.awtextra.AbsoluteConstraints(1053, 18, 270, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 1359, 841));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1398, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 876, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model=(DefaultTableModel) jTable1.getModel();
        if(jNameTablete.getSelectedItem() != "Select Doctor Ref"){
            model.addRow(new Object[]{
                jNameTablete.getSelectedItem(),
                jtxtRef1.getText(),
                jtxtFirstname.getText(),
                jtxtSurname.getText(),
                jtxtMedicalCenterName.getText(),
                jtxtPatientID.getText(),
                jtxAddressCenter.getText(),
                jtxtPostCode.getText(),
                jtxtMedicalCenterRef.getText(),
                jtxtOfficeMobNo1.getText(),
                jtxtOfficeMobNo2.getText(),
                jtxtFaxNo.getText(),
                jtxtEmailAddress.getText(),
                jtxtPatientNHS.getText(),
                jtxtEMISNo.getText(),
                jtxtGPAppintmentRef.getText(),
            });
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        if(jTable1.getSelectedRow()==-1){
            if(jTable1.getSelectedRow()==0){
                JOptionPane.showMessageDialog(null,"No data to delete","Medical Management System",JOptionPane.OK_OPTION);
            }
            else {
                JOptionPane.showMessageDialog(null,"Select a row to delete","Medical Management System",JOptionPane.OK_OPTION);
            }
        }
        else {
            model.removeRow(jTable1.getSelectedRow());
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        Help iHelp=new Help();
        iHelp.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        Login iLogin = new Login();
        iLogin.setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        JFrame frame = new JFrame("Exit");
        if(JOptionPane.showConfirmDialog(frame,"Confirm If you want to exit","Medical Management System",JOptionPane.YES_NO_OPTION )== JOptionPane.YES_NO_OPTION){
            setVisible(false);
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Medical iMedical = new Medical();
        iMedical.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jNameTableteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNameTableteActionPerformed
        // TODO add your handling code here:
        if(jNameTablete.getSelectedItem().equals("Select Doctor Ref")){
            jtxtGPAppintmentRef.setText("");
            jtxtFirstname.setText("");
            jtxtSurname.setText("");
            jtxtMedicalCenterName.setText("");
            jtxtPatientID.setText("");
            jtxAddressCenter.setText("");
            jtxtPostCode.setText("");
            jtxtMedicalCenterRef.setText("");
            jtxtOfficeMobNo1.setText("");
            jtxtOfficeMobNo2.setText("");
            jtxtFaxNo.setText("");
            jtxtEmailAddress.setText("");
            jtxtPatientNHS.setText("");
            jtxtEMISNo.setText("");
            jtxtGPAppintmentRef.setText("");
        }
        else if(jNameTablete.getSelectedItem().equals("DRRE983984")){
            jtxtRef1.setText("REF1800180221");
            jtxtFirstname.setText("Rajesh");
            jtxtSurname.setText("Jadhav");
            jtxtMedicalCenterName.setText("Shree Medical Center");
            jtxtPatientID.setText("PID7328492");
            jtxAddressCenter.setText("Near Ring Road");
            jtxtPostCode.setText("425001");
            jtxtMedicalCenterRef.setText("SHREE2839832");
            jtxtOfficeMobNo1.setText("9374727983");
            jtxtOfficeMobNo2.setText("9374727238");
            jtxtFaxNo.setText("+91 9373593732");
            jtxtEmailAddress.setText("RajeshJadhavdr20@gmail.com");
            jtxtPatientNHS.setText("7363762");
            jtxtEMISNo.setText("P973213");
            jtxtGPAppintmentRef.setText("791223");
        }
        else if(jNameTablete.getSelectedItem().equals("DRRE345678")) {
            jtxtRef1.setText("REF1800180194");
            jtxtFirstname.setText("ritik");
            jtxtSurname.setText("Thakur");
            jtxtMedicalCenterName.setText("Pankaj Medical Center");
            jtxtPatientID.setText("PID234567");
            jtxAddressCenter.setText("Khote Nagar");
            jtxtPostCode.setText("425002");
            jtxtMedicalCenterRef.setText("Pankaj3256487");
            jtxtOfficeMobNo1.setText("2364981290");
            jtxtOfficeMobNo2.setText("9047214587");
            jtxtFaxNo.setText("+91 2345765456");
            jtxtEmailAddress.setText("RitikThakur111@gmail.com");
            jtxtPatientNHS.setText("3456219");
            jtxtEMISNo.setText("P9663452");
            jtxtGPAppintmentRef.setText("567899");
        }
        else if(jNameTablete.getSelectedItem().equals("DRRE567833")){
            jtxtRef1.setText("REF1800180234");
            jtxtFirstname.setText("Raj");
            jtxtSurname.setText("Mahale");
            jtxtMedicalCenterName.setText("vedya Medical Center");
            jtxtPatientID.setText("PID456290");
            jtxAddressCenter.setText("RajaPeth");
            jtxtPostCode.setText("425003");
            jtxtMedicalCenterRef.setText("Vedya3256980");
            jtxtOfficeMobNo1.setText("4567328921");
            jtxtOfficeMobNo2.setText("4721985634");
            jtxtFaxNo.setText("+91 3623980633");
            jtxtEmailAddress.setText("RajMahale345@gmail.com");
            jtxtPatientNHS.setText("8532657");
            jtxtEMISNo.setText("P5612385");
            jtxtGPAppintmentRef.setText("234567");
        }
        else if(jNameTablete.getSelectedItem().equals("DRRE308164")){
            jtxtRef1.setText("REF1800180445");
            jtxtFirstname.setText("Girish");
            jtxtSurname.setText("Tayade");
            jtxtMedicalCenterName.setText("Jay Medical Center");
            jtxtPatientID.setText("PID342751");
            jtxAddressCenter.setText("Pratap Nagar");
            jtxtPostCode.setText("425004");
            jtxtMedicalCenterRef.setText("Jay4325610");
            jtxtOfficeMobNo1.setText("8552816537");
            jtxtOfficeMobNo2.setText("7249683132");
            jtxtFaxNo.setText("+91 3890213785 ");
            jtxtEmailAddress.setText("GirishTayade000@gmail.com");
            jtxtPatientNHS.setText("6891345");
            jtxtEMISNo.setText("P9011426");
            jtxtGPAppintmentRef.setText("442751");
        }
        else if(jNameTablete.getSelectedItem().equals("DRRE486100")){
            jtxtRef1.setText("REF1800180119");
            jtxtFirstname.setText("Amol");
            jtxtSurname.setText("Suryavanshi");
            jtxtMedicalCenterName.setText("Surya Medical Center");
            jtxtPatientID.setText("PID446281");
            jtxAddressCenter.setText("Balirampeth");
            jtxtPostCode.setText("425005");
            jtxtMedicalCenterRef.setText("Amol2784016");
            jtxtOfficeMobNo1.setText("8149314425");
            jtxtOfficeMobNo2.setText("4366720492");
            jtxtFaxNo.setText("+91 8557216493 ");
            jtxtEmailAddress.setText("Amol104@gmail.com");
            jtxtPatientNHS.setText("3451890");
            jtxtEMISNo.setText("P4378164");
            jtxtGPAppintmentRef.setText("857447");
        }

    }//GEN-LAST:event_jNameTableteActionPerformed

    private void jtxtRef1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtRef1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtRef1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Doctor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> jNameTablete;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jtxAddressCenter;
    private javax.swing.JTextField jtxtEMISNo;
    private javax.swing.JTextField jtxtEmailAddress;
    private javax.swing.JTextField jtxtFaxNo;
    private javax.swing.JTextField jtxtFirstname;
    private javax.swing.JTextField jtxtGPAppintmentRef;
    private javax.swing.JTextField jtxtMedicalCenterName;
    private javax.swing.JTextField jtxtMedicalCenterRef;
    private javax.swing.JTextField jtxtOfficeMobNo1;
    private javax.swing.JTextField jtxtOfficeMobNo2;
    private javax.swing.JTextField jtxtPatientID;
    private javax.swing.JTextField jtxtPatientNHS;
    private javax.swing.JTextField jtxtPostCode;
    private javax.swing.JTextField jtxtRef1;
    private javax.swing.JTextField jtxtSurname;
    // End of variables declaration//GEN-END:variables
}
